version: '3'
services:
  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network
    depends_on:
      - elasticsearch-api
      - rabbitmq-api
      - redis-api
    links:
      - elasticsearch-api
      - rabbitmq-api
      - redis-api
    env_file:
      - .env

  elasticsearch-api:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch-api
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  rabbitmq-api:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-api
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  redis-api:
    image: redis:7.0.5
    container_name: redis-api
    command: redis-server --requirepass redispw
    ports:
      - 6379:6379
    networks:
      - app-network
volumes:
  elasticsearch_data:

networks:
  app-network:
    driver: bridge
